apiVersion: v1
kind: Secret
metadata:
  name: {{ template "svk-userapp.fullname" . }}-secret
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: {{.Values.postgresql.postgresqlPassword | b64enc | quote}}
  DATABASE_URI: {{ printf "postgresql://%s:%s@%s-%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Release.Name .Values.postgresql.nameOverride .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | b64enc | quote }}

