apiVersion: v1
kind: Service
metadata:
  name: {{ include "svk-userapp.fullname" . }}
  labels:
    {{- include "svk-userapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.appDemo.spring.server.port}}
      protocol: TCP
      name: http
  selector:
    {{- include "svk-userapp.selectorLabels" . | nindent 4 }}
