# Default values for svk-userapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
  
postgresql: 
  enabled: true
  postgresqlPassword: qwerty1
  postgresqlDatabase: userdb
  postgresqlUsername: postgres
  service:
    port: "5432"
    type: NodePort
  nameOverride: "svk-database" 
  persistence:
    enabled: true
    size: "8Gi"

appDemo:
  spring:
#    datasource:
#      platform: "postgres"
#      url: "jdbc:postgresql://"
    server:
      port: 8000 

image:
  repository: svk1984/svk-h2
  #pullPolicy: IfNotPresent
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000 

service:
  ## Homework#2 demmo application service type
  ##
  type: NodePort
  port: 80

ingress:
  enabled: enable
  annotations: { 
    nginx.ingress.kubernetes.io/rewrite-target: /$2 ,
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/path"
    }

    #nginx.ingress.kubernetes.io/server-snippet: "location /otusapp/skharitonov/ {proxy_pass http://arch.homework; proxy_redirect default;}"
    #    nginx.org/location-snippets: "location ~* \"^/otusapp/skharitonov($|/)(.*)\"{ rewrite ^/otusapp/skharitonov/($|/)(.*) /$2 last;proxy_pass http://arch.homework; proxy_redirect default;}"

    #nginx.ingress.kubernetes.io/rewrite-target: /$2,
    # http://arch.homework/; proxy_redirect $scheme://$host:$server_port/ /otusapp/skharitonov/;

    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: arch.homework
      paths: [/otusapp/skharitonov($|/)(.*)]
      #paths: [/]
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
